### ISSUE TITLE
Could not initialize class com.koloboke.collect.map.hash.HashIntObjMaps$DefaultFactoryHolder

### ISSUE THREAD

**Issue by persal** [leventov/Koloboke#70]
Using AdoptOpenJDK 11.0.5
First of all, is ver 1.0.0 compatible with JDK 11?

We get a NoClassDefFoundError with below stacktrace:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.koloboke.collect.map.hash.HashIntObjMaps$DefaultFactoryHolder
	at com.koloboke.collect.map.hash.HashIntObjMaps.getDefaultFactory(HashIntObjMaps.java:55) ~[koloboke-api-jdk8-1.0.0.jar:?]
	at com.koloboke.collect.map.hash.HashIntObjMaps.newImmutableMap(HashIntObjMaps.java:1499) ~[koloboke-api-jdk8-1.0.0.jar:?]

Code that breaks:
TreeMap<Integer, DeserializeAction> map = new TreeMap<>();
..do stuff
this.map = HashIntObjMaps.newImmutableMap(map); //this line throws exception

The above code is initiated in a class in its initialization
public class Myclass {
DoStuff stuff = new DoStuff();  // triggers the above call to  HashIntObjMaps.newImmutableMap(map);

}

We have following jar files in the classpath:
koloboke-api-jdk8-1.0.0.jar
koloboke-impl-common-jdk8-1.0.0.jar
koloboke-impl-jdk8-1.0.0.jar

We have not been able to reproduce it consequently, but seem to happen from time to time.

**Comment by persal** [comment]
Understand this project is not actively being developed any more, but for the record the above issue has been solved and has nothing to do with this library but with another library managing the classloading.

**Comment by Vince-amat** [comment]
Hello @persal 
I know this is on old subject but can you be more specific about how you solved the issue ? I have the same issue in one of my project (base on springboot). But It does not appear in another project (not spring bott related). 
I'm not saying spring boot can be a cause, just to add more precision.

What was the library you mentioned ? How did you do to identify the problem ?

Thx in advance !

**Comment by Vince-amat** [comment]
Copilot may have found my error :)

> This error is caused by a race condition during Koloboke library initialization in a multi-threaded environment (ForkJoinPool).

The implementation was initialized in multiple threads (used in` stream().parallel()`).

Several solutions:
- Force Initialization at Startup
```java
import com.koloboke.collect.map.hash.HashLongObjMaps;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class KolobokeInitializer {

    @Bean
    public String initKoloboke() {
        // Force Koloboke initialization at application startup
        HashLongObjMaps.newMutableMap();
        return "Koloboke initialized";
    }
}
```

- Remove Parallel Processing
```java
item.stream()
       .parallel()  // ← Remove .parallel()
       .map(...)
       .toList();
```

- Synchronize Initialization
```java
private static final Object KOLOBOKE_INIT_LOCK = new Object();
private static volatile boolean kolobokeInitialized = false;

private void ensureKolobokeInitialized() {
    if (!kolobokeInitialized) {
        synchronized (KOLOBOKE_INIT_LOCK) {
            if (!kolobokeInitialized) {
                HashLongObjMaps.newMutableMap();
                kolobokeInitialized = true;
            }
        }
    }
}

// Call this at the beginning of your method
public void method(Input input) {
    ensureKolobokeInitialized();
    // ... rest of code
}
```

**Comment by persal** [comment]
You can find the root cause and solution of my issue here https://github.com/update4j/update4j/issues/75
